[package]
name = "rizubot-discord"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
dotenvy = "0.15.7"
poise = "0.6.2"
reqwest = { version = "0.12", features = ["json"] }
serde = "1.0.229"
serde_json = "1.0.151"
serenity = "0.12.5"
songbird = { version = "0.6", features = ["serenity", "builtin-queue"] }
symphonia = { version = "0.5", features = ["all"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "1.52.3", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
codegen-units = 1 # Reduces memory usage by doing less parallel codegen
opt-level = "s" # Optimize for size to reduce build time/memory (optional, but 'z' or 's' helps)
debug = false # Disable debug symbols
strip = true # Strip symbols from the binary
lto = false # Disable link-time optimization (reduces memory during linking)
